version: 2

models:
  - name: fact_sales
    description: Fact table which contains ecommerce sales.
    columns:

    - name: quantity
      tests:
        - positive_value

    - name: unitprice
      tests:
        - positive_value
        - dbt_expectations.expect_column_max_to_be_between:
            max_value: 1000


    # - name: country
    #   tests:
    #     - not_null









  # - name: dim_products
  #   tests:
  #     - dbt_expectations.expect_table_row_count_to_equal_other_table:
  #         compare_model: ref('raw_sales')

  #   columns:
  #     - name: PRODUCTCODE
  #       tests:
  #         - relationships:
  #             to: ref('fact_sales')
  #             field: PRODUCTCODE


  # - name: fact_sales
  #   description: List of historical sales.
  #   tests:
  #     - dbt_expectations.expect_table_row_count_to_equal_other_table:
  #         compare_model: ref('raw_sales')

  #   columns:
  
  #   - name: dealsize
  #     tests:
  #       - not_null
  #       - accepted_values:
  #           values: ['Small', 'Medium', 'Large']
    
  #   - name: status
  #     description: Indicates the status of the sales order.
  #     tests:
  #       - not_null
  #       - accepted_values:
  #           values: ['Shipped', 'In Process', 'Disputed', 'Cancelled', 'On Hold', 'Resolved']
    
  #   - name: amount
  #     description: '{{ doc("fact_sales") }}'
  #     tests:
  #       - positive_value
    
  #   - name: unitprice
  #     tests:
  #       - dbt_expectations.expect_column_values_to_be_of_type:
  #           column_type: number
  #       - dbt_expectations.expect_column_quantile_values_to_be_between:
  #           quantile: .99
  #           min_value: 50
  #           max_value: 300
  #       - dbt_expectations.expect_column_max_to_be_between:
  #           max_value: 1000
  #           config:
  #             severity: warn

    

  