version: 2

sources:
  - name: ecommerce
    schema: raw
    tables:
      - name: sales_ecomm
        identifier: sales
        loaded_at_field: INVOICEDATE
        freshness:
          warn_after: {count: 1, period: day}